version: 0.2

phases:
  build:
    commands:
      - |
        echo "Resolving git tag..."
        if [ "$GIT_TAG" = "None" ]; then
          GIT_TAG=$(git describe --tags --exact-match "$CODEBUILD_RESOLVED_SOURCE_VERSION" 2>/dev/null)
          if [ -n "$GIT_TAG" ]; then
            git checkout "$GIT_TAG"
          else
            echo "No matching tag found for $CODEBUILD_RESOLVED_SOURCE_VERSION"
            exit 1
          fi
        else
          git checkout "$GIT_TAG"
        fi

        if [ "$BUILD_PHASE" = "scan" ]; then
          echo "Installing Trivy..."
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.58.2

          echo "Running Trivy security scan..."
          trivy config --skip-dirs examples .
        elif [ "$BUILD_PHASE" = "deploy" ]; then
          echo "Uploading module to S3..."
          zip terraform-module.zip . -x "./.git/*" "./.dcg/*" "./.github/*" "./examples/*" "./.terraform/*"
          aws s3 cp terraform-module.zip s3://${S3_MODULE_BUCKET}/${MODULE_NAME}/${GIT_TAG}.zip --region ${AWS_REGION}
        else
          echo "Build phase invalid.. exiting"
          exit 1
        fi
