version: 0.2

phases:
  build:
    commands:
      - |
        if echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | grep -Eq "^[a-f0-9]{40}$"; then
          echo "Detected a commit hash: $CODEBUILD_RESOLVED_SOURCE_VERSION"
        else
          echo "Detected a Git tag: $CODEBUILD_RESOLVED_SOURCE_VERSION"
        fi

        echo "TESTTESTTESTTESTTESTTESTTESTTESTTEST"
        if [ "$BUILD_PHASE" = "scan" ]; then
          echo "Installing Trivy..."
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.58.2

          echo "Running Trivy security scan..."
          trivy config --skip-dirs examples .
        elif [ "$BUILD_PHASE" = "deploy" ]; then
          echo "Uploading module to S3..."
          echo "${S3_MODULE_BUCKET}/${MODULE_NAME}/${CODEBUILD_RESOLVED_SOURCE_VERSION}"
          # aws s3 cp terraform-module.zip s3://${S3_MODULE_BUCKET}/${MODULE_NAME}/${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip --region ${AWS_REGION}
        else
          echo "Build phase invalid.. exiting"
          exit 1
        fi
